name: Deploy to GoDaddy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: "20"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install and build
        run: |
          npm ci
          npm run build
        env:
          NEXT_PUBLIC_SITE_URL: https://jsilverman.ca

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Create archive and upload
        run: |
          cd out
          tar -czf ../site.tar.gz .
          cd ..
          scp -o StrictHostKeyChecking=no site.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/

      - name: Check server directories
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking directory structure..."
            ls -la ~/
            echo "Looking for web directories..."
            find ~ -maxdepth 2 -type d -name "*html*" -o -name "*www*" -o -name "*web*" 2>/dev/null || true

            - name: Debug directory structure and deploy everywhere
            uses: appleboy/ssh-action@v1.0.0
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                echo "=== DEBUGGING DIRECTORY STRUCTURE ==="
                
                echo "1. Home directory contents:"
                ls -la ~/
                
                echo "2. Looking for ALL web-related directories:"
                find ~ -maxdepth 3 -type d \( -name "*html*" -o -name "*www*" -o -name "*web*" -o -name "*httpdocs*" \) 2>/dev/null || true
                
                echo "3. Checking if domains are configured in cPanel:"
                find ~ -name "*.conf" -o -name "*domain*" 2>/dev/null | head -5 || true
                
                echo "4. Current public_html contents:"
                ls -la ~/public_html/ 2>/dev/null || echo "public_html does not exist"
                
                echo "=== DEPLOYING TO MULTIPLE LOCATIONS ==="
                
                # Deploy to standard public_html
                mkdir -p ~/public_html
                cd ~/public_html
                rm -rf *
                tar -xzf ~/site.tar.gz
                echo "Deployed to ~/public_html - files:"
                ls -la
                
                # Deploy to httpdocs if it exists (some GoDaddy setups use this)
                if [ -d ~/httpdocs ]; then
                  echo "Found httpdocs directory, deploying there too..."
                  cd ~/httpdocs
                  rm -rf *
                  tar -xzf ~/site.tar.gz
                  echo "Deployed to ~/httpdocs - files:"
                  ls -la
                fi
                
                # Deploy to www if it exists
                if [ -d ~/www ]; then
                  echo "Found www directory, deploying there too..."
                  cd ~/www
                  rm -rf *
                  tar -xzf ~/site.tar.gz
                  echo "Deployed to ~/www - files:"
                  ls -la
                fi
                
                # Check if there's a domains-specific directory
                if [ -d ~/domains ]; then
                  echo "Found domains directory:"
                  ls -la ~/domains/
                fi
                
                echo "=== SETTING PERMISSIONS EVERYWHERE ==="
                find ~/public_html -type f -exec chmod 644 {} \; 2>/dev/null || true
                find ~/public_html -type d -exec chmod 755 {} \; 2>/dev/null || true
                find ~/httpdocs -type f -exec chmod 644 {} \; 2>/dev/null || true
                find ~/httpdocs -type d -exec chmod 755 {} \; 2>/dev/null || true
                find ~/www -type f -exec chmod 644 {} \; 2>/dev/null || true
                find ~/www -type d -exec chmod 755 {} \; 2>/dev/null || true
                
                rm ~/site.tar.gz
                echo "=== DEPLOYMENT COMPLETE ==="

      - name: Create htaccess
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/public_html
            cat > .htaccess << 'EOF'
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
            EOF
            echo "htaccess created"

      - name: Verify deployment
        run: |
          echo "Deployment complete"
          echo "Check https://jsilverman.ca in a few minutes"
